In [2]:

import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

scores:ndarray | None = None # 學生的分數
scores_df:DataFrame | None = None # 學生分數的DataFrame

scores = np.random.randint(50, 101, size=(50, 5))
scores_df = pd.DataFrame(scores,            
            columns=['國文', '英文', '數學', '地理', '歷史'],
            index=range(1,51))

names_df:DataFrame = pd.read_csv('students.csv')
scores_df[['姓名','性別']] = names_df[['姓名','性別']].head(n=50).values
scores_df = scores_df[['姓名', '性別','國文', '英文', '數學', '地理', '歷史']]
scores_df

     姓名 性別  國文   英文   數學   地理  歷史
1   劉彥宏  男  87   84   83   93  57
2   曾彥廷  男  94  100   56   79  78
3   吳子睿  男  62   71   86   63  62
4   蕭志明  男  68   91   77   61  85
5   王文傑  男  51   51   83   83  93
6   朱冠霖  男  70   50   72   65  82
7   謝欣蓉  女  83  100  100   60  90
8   羅淑芬  女  70   71   82   91  84
9   許美慧  女  95   61   89  100  53
10  廖志豪  男  62   93   53   82  82
11  葉柏翰  男  90   59   93   94  74
12  呂承恩  男  58   77   88   98  67
13  蘇雅婷  女  81   61   50   61  59
14  高浩宇  男  68   68  100   69  87
15  王婉茹  女  56   57   84   80  51
16  莊承翰  男  96   55   77   51  97
17  黃裕傑  男  64   99   91   70  60
18  王冠廷  男  80   85   77   58  72
19  呂婉慧  女  60   90   75   67  87
20  莊子謙  男  78   57   74   54  92
21  蘇彥宏  男  96   67   91   83  57
22  李柏融  男  71   73   86   76  76
23  曾明軒  男  92   83   80   71  50
24  呂佳瑩  女  99   71   53   51  74
25  洪怡君  女  92   94   92   91  61
26  洪柏宏  男  86   54   73   63  99
27  江雅琪  女  74   93   61   96  55
28  郭怡萱  女  59   51   84   64  75
29  簡婉慧  女  62   98   53   56  58
30  楊靜宜  女  79   83   52   60  82
31  曾靜儀  女  91   73   82   51  97
32  蕭怡伶  女  89   87   61   80  66
33  洪裕豪  男  72   97   91   98  76
34  簡建宏  男  62   66   73   74  93
35  劉浩然  男  79   59   75   70  73
36  蕭浩宇  男  53   77   74   63  82
37  呂怡靜  女  54   93   56   90  99
38  邱宗翰  男  51   93  100   88  74
39  彭美慧  女  80   95   53   74  90
40  劉靜芬  女  71   68  100   50  91
41  許淑芬  女  84   56   50   60  80
42  邱裕豪  男  57   86   60   81  94
43  吳雅萍  女  95   86   58   73  85
44  施子軒  男  76   97   68   55  55
45  莊柏融  男  98   87   90   63  99
46  鍾浩銘  男  89   58   91   78  92
47  周美玲  女  52   64   77   62  71
48  劉婉婷  女  79   96   80   54  69
49  曾明哲  男  50   53   63   57  89
50  詹柏翰  男  65   51   55   54  61

In [3]:
import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

scores:ndarray | None = None # 學生的分數
scores_df:DataFrame | None = None # 學生分數的DataFrame

scores = np.random.randint(50, 101, size=(50, 5))
scores_df = pd.DataFrame(scores,            
            columns=['國文', '英文', '數學', '地理', '歷史'],
            index=range(1,51))

names_df:DataFrame = pd.read_csv('students.csv')
scores_df[['姓名','性別']] = names_df[['姓名','性別']].head(n=50).values
scores_df = scores_df[['姓名', '性別','國文', '英文', '數學', '地理', '歷史']]
#選取欄
scores_df[['姓名','國文']]
#選取列
scores_df.iloc[5]
scores_df.iloc[5:10]

     姓名 性別  國文  英文  數學  地理  歷史
6   朱冠霖  男  68  90  71  67  55
7   謝欣蓉  女  55  76  86  99  59
8   羅淑芬  女  52  71  79  73  68
9   許美慧  女  70  64  88  84  77
10  廖志豪  男  96  79  64  99  76

In [4]:
import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

#scores:ndarray | None = None # 學生的分數
#scores_df:DataFrame | None = None # 學生分數的DataFrame

scores:ndarray = np.random.randint(40, 101, size=(50, 5))
scores_df:DataFrame = pd.DataFrame(scores,            
            columns=['國文', '英文', '數學', '地理', '歷史'],
            index=range(1,51))

names_df:DataFrame = pd.read_csv('students.csv')
scores_df[['姓名','性別']] = names_df[['姓名','性別']].head(n=50).values
scores_df = scores_df[['姓名', '性別','國文', '英文', '數學', '地理', '歷史']]
#選取欄
scores_df[['姓名','國文']]
#選取列
scores_df.iloc[5]
scores_df.iloc[5:10]

     姓名 性別  國文  英文  數學  地理  歷史
6   朱冠霖  男  96  58  75  74  73
7   謝欣蓉  女  94  82  64  95  96
8   羅淑芬  女  83  46  48  44  70
9   許美慧  女  60  75  65  79  83
10  廖志豪  男  90  47  80  74  88

In [5]:
scores_df[scores_df['姓名'] == '許美慧']
scores_df[scores_df['國文'] < 60]

     姓名 性別  國文  英文  數學  地理   歷史
1   劉彥宏  男  45  50  49  41   84
3   吳子睿  男  52  58  40  41   82
4   蕭志明  男  57  84  53  98   61
13  蘇雅婷  女  42  69  72  65   43
14  高浩宇  男  54  52  97  87   97
16  莊承翰  男  47  56  94  77   87
20  莊子謙  男  57  50  63  52   78
22  李柏融  男  42  89  43  78   74
23  曾明軒  男  53  61  59  78   69
28  郭怡萱  女  44  64  96  95   83
29  簡婉慧  女  49  98  63  81   92
33  洪裕豪  男  53  90  74  65   86
36  蕭浩宇  男  45  70  41  85  100
39  彭美慧  女  58  58  54  83   97
40  劉靜芬  女  58  74  93  41   45
41  許淑芬  女  51  51  70  79   92
47  周美玲  女  41  84  71  89   95
50  詹柏翰  男  49  62  48  92   97

In [7]:
scores_df.query('國文 < 60 and 性別 == "女"')

     姓名 性別  國文  英文  數學  地理  歷史
13  蘇雅婷  女  42  69  72  65  43
28  郭怡萱  女  44  64  96  95  83
29  簡婉慧  女  49  98  63  81  92
39  彭美慧  女  58  58  54  83  97
40  劉靜芬  女  58  74  93  41  45
41  許淑芬  女  51  51  70  79  92
47  周美玲  女  41  84  71  89  95

In [8]:
scores_df[scores_df['姓名'] == '許美慧']
scores_df[scores_df['國文'] < 60]
scores_df.query("性別 == '女' and 國文 < 60 ")

     姓名 性別  國文  英文  數學  地理  歷史
13  蘇雅婷  女  42  69  72  65  43
28  郭怡萱  女  44  64  96  95  83
29  簡婉慧  女  49  98  63  81  92
39  彭美慧  女  58  58  54  83  97
40  劉靜芬  女  58  74  93  41  45
41  許淑芬  女  51  51  70  79  92
47  周美玲  女  41  84  71  89  95

In [9]:
scores_df["總分"] = scores_df[['國文', '英文', '數學', '地理', '歷史']].sum(axis=1)
scores_df["平均"] = scores_df[['國文', '英文', '數學', '地理', '歷史']].mean(axis=1)
scores_df["排名"] = scores_df["總分"].rank(ascending=False,method='min')
scores_df.sort_values(by='排名')

     姓名 性別  國文  英文   數學   地理   歷史   總分    平均    排名
19  呂婉慧  女  90  89   95   94   89  457  91.4   1.0
7   謝欣蓉  女  94  82   64   95   96  431  86.2   2.0
43  吳雅萍  女  95  92   77   87   73  424  84.8   3.0
26  洪柏宏  男  63  57   90   94   88  392  78.4   4.0
30  楊靜宜  女  96  78   86   55   76  391  78.2   5.0
27  江雅琪  女  70  75   94   70   81  390  78.0   6.0
24  呂佳瑩  女  73  95   68   56   96  388  77.6   7.0
14  高浩宇  男  54  52   97   87   97  387  77.4   8.0
42  邱裕豪  男  71  68   72  100   73  384  76.8   9.0
29  簡婉慧  女  49  98   63   81   92  383  76.6  10.0
28  郭怡萱  女  44  64   96   95   83  382  76.4  11.0
47  周美玲  女  41  84   71   89   95  380  76.0  12.0
10  廖志豪  男  90  47   80   74   88  379  75.8  13.0
32  蕭怡伶  女  98  50   96   83   50  377  75.4  14.0
6   朱冠霖  男  96  58   75   74   73  376  75.2  15.0
18  王冠廷  男  82  41   94   72   83  372  74.4  16.0
33  洪裕豪  男  53  90   74   65   86  368  73.6  17.0
12  呂承恩  男  90  43  100   47   87  367  73.4  18.0
9   許美慧  女  60  75   65   79   83  362  72.4  19.0
16  莊承翰  男  47  56   94   77   87  361  72.2  20.0
11  葉柏翰  男  70  97   68   64   61  360  72.0  21.0
21  蘇彥宏  男  73  79   48   71   86  357  71.4  22.0
37  呂怡靜  女  72  48   67   82   88  357  71.4  22.0
5   王文傑  男  82  98   44   70   60  354  70.8  24.0
48  劉婉婷  女  98  50   77   87   41  353  70.6  25.0
4   蕭志明  男  57  84   53   98   61  353  70.6  25.0
44  施子軒  男  80  58  100   58   55  351  70.2  27.0
39  彭美慧  女  58  58   54   83   97  350  70.0  28.0
38  邱宗翰  男  76  60   87   68   57  348  69.6  29.0
50  詹柏翰  男  49  62   48   92   97  348  69.6  29.0
34  簡建宏  男  61  61   92   59   75  348  69.6  29.0
25  洪怡君  女  63  57   76   92   57  345  69.0  32.0
49  曾明哲  男  88  85   77   55   40  345  69.0  32.0
41  許淑芬  女  51  51   70   79   92  343  68.6  34.0
36  蕭浩宇  男  45  70   41   85  100  341  68.2  35.0
2   曾彥廷  男  78  60   73   53   67  331  66.2  36.0
22  李柏融  男  42  89   43   78   74  326  65.2  37.0
46  鍾浩銘  男  68  50   59   70   75  322  64.4  38.0
45  莊柏融  男  61  84   89   40   48  322  64.4  38.0
23  曾明軒  男  53  61   59   78   69  320  64.0  40.0
15  王婉茹  女  61  59   69   45   81  315  63.0  41.0
31  曾靜儀  女  74  64   51   59   65  313  62.6  42.0
40  劉靜芬  女  58  74   93   41   45  311  62.2  43.0
35  劉浩然  男  64  76   56   62   47  305  61.0  44.0
20  莊子謙  男  57  50   63   52   78  300  60.0  45.0
8   羅淑芬  女  83  46   48   44   70  291  58.2  46.0
13  蘇雅婷  女  42  69   72   65   43  291  58.2  46.0
3   吳子睿  男  52  58   40   41   82  273  54.6  48.0
17  黃裕傑  男  96  41   43   48   43  271  54.2  49.0
1   劉彥宏  男  45  50   49   41   84  269  53.8  50.0