In [8]:

import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

scores:ndarray | None = None # 學生的分數
scores_df:DataFrame | None = None # 學生分數的DataFrame

scores = np.random.randint(50, 101, size=(50, 5))
scores_df = pd.DataFrame(scores,            
            columns=['國文', '英文', '數學', '地理', '歷史'],
            index=range(1,51))

names_df:DataFrame = pd.read_csv('students.csv')
scores_df[['姓名','性別']] = names_df[['姓名','性別']].head(n=50).values
scores_df = scores_df[['姓名', '性別','國文', '英文', '數學', '地理', '歷史']]
scores_df

     姓名 性別  國文   英文   數學  地理   歷史
1   劉彥宏  男  89   88   57  53   94
2   曾彥廷  男  66   62   60  66  100
3   吳子睿  男  74   76   88  90   52
4   蕭志明  男  59   77   92  81   57
5   王文傑  男  70   94   73  71  100
6   朱冠霖  男  99   71   67  86   53
7   謝欣蓉  女  85   72   93  74   54
8   羅淑芬  女  97   97   61  62   89
9   許美慧  女  79   85   97  96   58
10  廖志豪  男  86   62  100  96   56
11  葉柏翰  男  88   99   71  94   92
12  呂承恩  男  71   96   66  67   71
13  蘇雅婷  女  76   79   92  70   93
14  高浩宇  男  94   71   97  98   90
15  王婉茹  女  77   60   90  93   72
16  莊承翰  男  95   97   92  51   50
17  黃裕傑  男  89   94   99  52   68
18  王冠廷  男  62   62   55  82   66
19  呂婉慧  女  66   89   50  63   50
20  莊子謙  男  86   89   82  67   54
21  蘇彥宏  男  65   68   94  63   66
22  李柏融  男  67   84   92  54   73
23  曾明軒  男  85   69   85  78   64
24  呂佳瑩  女  77   98   78  86   80
25  洪怡君  女  71   98   76  59   79
26  洪柏宏  男  54   71   72  90   63
27  江雅琪  女  91   97   86  70   90
28  郭怡萱  女  93   62   57  73   66
29  簡婉慧  女  67   84   62  83   77
30  楊靜宜  女  56   73   88  84   50
31  曾靜儀  女  57  100   79  96   75
32  蕭怡伶  女  63   66   95  62   54
33  洪裕豪  男  93   88   54  70   51
34  簡建宏  男  74   93   85  99   67
35  劉浩然  男  94   63   50  90   80
36  蕭浩宇  男  86   97   51  73   73
37  呂怡靜  女  88   73   66  54   93
38  邱宗翰  男  89   59   53  83   65
39  彭美慧  女  89   73   72  89   86
40  劉靜芬  女  71   64   53  66   70
41  許淑芬  女  86   63   71  69   52
42  邱裕豪  男  95   65   57  58   74
43  吳雅萍  女  59   81   85  53   68
44  施子軒  男  51   61   91  77   68
45  莊柏融  男  96   84   60  86   58
46  鍾浩銘  男  51   85   58  76   80
47  周美玲  女  55   97   58  70   70
48  劉婉婷  女  99   72   64  68   76
49  曾明哲  男  71   85   89  64   61
50  詹柏翰  男  76   75   91  54   60

In [9]:
import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

#scores:ndarray | None = None # 學生的分數
#scores_df:DataFrame | None = None # 學生分數的DataFrame

scores:ndarray = np.random.randint(40, 101, size=(50, 5))
scores_df:DataFrame = pd.DataFrame(scores,            
            columns=['國文', '英文', '數學', '地理', '歷史'],
            index=range(1,51))

names_df:DataFrame = pd.read_csv('students.csv')
scores_df[['姓名','性別']] = names_df[['姓名','性別']].head(n=50).values
scores_df = scores_df[['姓名', '性別','國文', '英文', '數學', '地理', '歷史']]
#選取欄
scores_df[['姓名','國文']]
#選取列
scores_df.iloc[5]
scores_df.iloc[5:10]

     姓名 性別  國文   英文  數學  地理  歷史
6   朱冠霖  男  48   96  43  42  93
7   謝欣蓉  女  90  100  47  41  68
8   羅淑芬  女  85   97  82  98  82
9   許美慧  女  88   62  91  85  61
10  廖志豪  男  98   96  71  48  59

In [10]:
scores_df[scores_df['姓名'] == '許美慧']
scores_df[scores_df['國文'] < 60]
scores_df.query("性別 == '女' and 國文 < 60 ")

     姓名 性別  國文  英文  數學  地理  歷史
19  呂婉慧  女  59  75  75  73  86
24  呂佳瑩  女  50  65  98  94  80
25  洪怡君  女  43  44  82  91  91
27  江雅琪  女  48  95  95  68  55
28  郭怡萱  女  57  53  79  47  86
31  曾靜儀  女  44  55  73  84  85
39  彭美慧  女  56  60  48  72  98
40  劉靜芬  女  46  46  49  55  96
43  吳雅萍  女  42  62  55  95  44
47  周美玲  女  52  45  44  98  96

In [11]:

scores_df["總分"] = scores_df[['國文', '英文', '數學', '地理', '歷史']].sum(axis=1)
scores_df["平均"] = scores_df[['國文', '英文', '數學', '地理', '歷史']].mean(axis=1)
scores_df["排名"] = scores_df["總分"].rank(ascending=False,method='min')
scores_df.sort_values(by='排名')

     姓名 性別   國文   英文  數學   地理   歷史   總分    平均    排名
8   羅淑芬  女   85   97  82   98   82  444  88.8   1.0
44  施子軒  男   75   79  90   92   83  419  83.8   2.0
34  簡建宏  男   76   63  79   90  100  408  81.6   3.0
23  曾明軒  男  100   83  70   81   66  400  80.0   4.0
1   劉彥宏  男   99   72  86   55   84  396  79.2   5.0
18  王冠廷  男   96   88  53   58   93  388  77.6   6.0
9   許美慧  女   88   62  91   85   61  387  77.4   7.0
24  呂佳瑩  女   50   65  98   94   80  387  77.4   7.0
20  莊子謙  男   48   82  97   59   98  384  76.8   9.0
37  呂怡靜  女   82   72  97   56   70  377  75.4  10.0
26  洪柏宏  男   71   87  86   63   67  374  74.8  11.0
10  廖志豪  男   98   96  71   48   59  372  74.4  12.0
48  劉婉婷  女   75   41  94   99   61  370  74.0  13.0
11  葉柏翰  男   83   98  83   53   52  369  73.8  14.0
19  呂婉慧  女   59   75  75   73   86  368  73.6  15.0
30  楊靜宜  女   61   99  55   62   87  364  72.8  16.0
46  鍾浩銘  男   64   65  50   99   85  363  72.6  17.0
27  江雅琪  女   48   95  95   68   55  361  72.2  18.0
42  邱裕豪  男   54   81  67   62   94  358  71.6  19.0
38  邱宗翰  男   80   59  92   66   61  358  71.6  19.0
16  莊承翰  男   54   61  72   92   79  358  71.6  19.0
5   王文傑  男   41   55  89   92   78  355  71.0  22.0
12  呂承恩  男   88   52  54   65   94  353  70.6  23.0
15  王婉茹  女   83   87  46   69   67  352  70.4  24.0
41  許淑芬  女   79   64  97   55   56  351  70.2  25.0
25  洪怡君  女   43   44  82   91   91  351  70.2  25.0
7   謝欣蓉  女   90  100  47   41   68  346  69.2  27.0
3   吳子睿  男   86   74  73   56   54  343  68.6  28.0
31  曾靜儀  女   44   55  73   84   85  341  68.2  29.0
4   蕭志明  男   60   49  89  100   42  340  68.0  30.0
47  周美玲  女   52   45  44   98   96  335  67.0  31.0
39  彭美慧  女   56   60  48   72   98  334  66.8  32.0
17  黃裕傑  男   59   63  68   42  100  332  66.4  33.0
13  蘇雅婷  女   92   47  45   93   49  326  65.2  34.0
32  蕭怡伶  女   62   52  84   42   86  326  65.2  34.0
28  郭怡萱  女   57   53  79   47   86  322  64.4  36.0
14  高浩宇  男   61   99  54   50   58  322  64.4  36.0
6   朱冠霖  男   48   96  43   42   93  322  64.4  36.0
2   曾彥廷  男   67   63  63   67   57  317  63.4  39.0
49  曾明哲  男   50   47  70   73   76  316  63.2  40.0
29  簡婉慧  女   60   77  50   65   60  312  62.4  41.0
33  洪裕豪  男   46   50  98   52   62  308  61.6  42.0
21  蘇彥宏  男   42   95  49   45   76  307  61.4  43.0
36  蕭浩宇  男   58   55  73   63   54  303  60.6  44.0
45  莊柏融  男   47   41  80   49   81  298  59.6  45.0
43  吳雅萍  女   42   62  55   95   44  298  59.6  45.0
40  劉靜芬  女   46   46  49   55   96  292  58.4  47.0
50  詹柏翰  男   45   49  93   47   47  281  56.2  48.0
35  劉浩然  男   48   48  40   59   51  246  49.2  49.0
22  李柏融  男   43   40  55   48   51  237  47.4  50.0

In [12]:
from pandas import Series
def calulate(s:Series)-> int:
    n = (s < 60).sum()
    return n
    
scores_df['及格的科目數'] = scores_df[['國文', '英文', '數學', '地理', '歷史']].apply(calulate,axis=1)
scores_df

     姓名 性別   國文   英文  數學   地理   歷史   總分    平均    排名  及格的科目數
1   劉彥宏  男   99   72  86   55   84  396  79.2   5.0       1
2   曾彥廷  男   67   63  63   67   57  317  63.4  39.0       1
3   吳子睿  男   86   74  73   56   54  343  68.6  28.0       2
4   蕭志明  男   60   49  89  100   42  340  68.0  30.0       2
5   王文傑  男   41   55  89   92   78  355  71.0  22.0       2
6   朱冠霖  男   48   96  43   42   93  322  64.4  36.0       3
7   謝欣蓉  女   90  100  47   41   68  346  69.2  27.0       2
8   羅淑芬  女   85   97  82   98   82  444  88.8   1.0       0
9   許美慧  女   88   62  91   85   61  387  77.4   7.0       0
10  廖志豪  男   98   96  71   48   59  372  74.4  12.0       2
11  葉柏翰  男   83   98  83   53   52  369  73.8  14.0       2
12  呂承恩  男   88   52  54   65   94  353  70.6  23.0       2
13  蘇雅婷  女   92   47  45   93   49  326  65.2  34.0       3
14  高浩宇  男   61   99  54   50   58  322  64.4  36.0       3
15  王婉茹  女   83   87  46   69   67  352  70.4  24.0       1
16  莊承翰  男   54   61  72   92   79  358  71.6  19.0       1
17  黃裕傑  男   59   63  68   42  100  332  66.4  33.0       2
18  王冠廷  男   96   88  53   58   93  388  77.6   6.0       2
19  呂婉慧  女   59   75  75   73   86  368  73.6  15.0       1
20  莊子謙  男   48   82  97   59   98  384  76.8   9.0       2
21  蘇彥宏  男   42   95  49   45   76  307  61.4  43.0       3
22  李柏融  男   43   40  55   48   51  237  47.4  50.0       5
23  曾明軒  男  100   83  70   81   66  400  80.0   4.0       0
24  呂佳瑩  女   50   65  98   94   80  387  77.4   7.0       1
25  洪怡君  女   43   44  82   91   91  351  70.2  25.0       2
26  洪柏宏  男   71   87  86   63   67  374  74.8  11.0       0
27  江雅琪  女   48   95  95   68   55  361  72.2  18.0       2
28  郭怡萱  女   57   53  79   47   86  322  64.4  36.0       3
29  簡婉慧  女   60   77  50   65   60  312  62.4  41.0       1
30  楊靜宜  女   61   99  55   62   87  364  72.8  16.0       1
31  曾靜儀  女   44   55  73   84   85  341  68.2  29.0       2
32  蕭怡伶  女   62   52  84   42   86  326  65.2  34.0       2
33  洪裕豪  男   46   50  98   52   62  308  61.6  42.0       3
34  簡建宏  男   76   63  79   90  100  408  81.6   3.0       0
35  劉浩然  男   48   48  40   59   51  246  49.2  49.0       5
36  蕭浩宇  男   58   55  73   63   54  303  60.6  44.0       3
37  呂怡靜  女   82   72  97   56   70  377  75.4  10.0       1
38  邱宗翰  男   80   59  92   66   61  358  71.6  19.0       1
39  彭美慧  女   56   60  48   72   98  334  66.8  32.0       2
40  劉靜芬  女   46   46  49   55   96  292  58.4  47.0       4
41  許淑芬  女   79   64  97   55   56  351  70.2  25.0       2
42  邱裕豪  男   54   81  67   62   94  358  71.6  19.0       1
43  吳雅萍  女   42   62  55   95   44  298  59.6  45.0       3
44  施子軒  男   75   79  90   92   83  419  83.8   2.0       0
45  莊柏融  男   47   41  80   49   81  298  59.6  45.0       3
46  鍾浩銘  男   64   65  50   99   85  363  72.6  17.0       1
47  周美玲  女   52   45  44   98   96  335  67.0  31.0       3
48  劉婉婷  女   75   41  94   99   61  370  74.0  13.0       1
49  曾明哲  男   50   47  70   73   76  316  63.2  40.0       2
50  詹柏翰  男   45   49  93   47   47  281  56.2  48.0       4

In [ ]:
def get_failing_subjects(row):
    subjects = ['國文', '英文', '數學', '地理', '歷史']
    failing = [subj for subj in subjects if row[subj] < 60]    
    return ','.join(failing) if failing else "無"
    
    
scores_df["不及格的科目名稱"] = scores_df[['國文', '英文', '數學', '地理', '歷史']].apply(get_failing_subjects,axis=1)
scores_df

In [3]:
import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

scores:ndarray | None = None # 學生的分數
scores_df:DataFrame | None = None # 學生分數的DataFrame

scores = np.random.randint(50, 101, size=(50, 5))
scores_df = pd.DataFrame(scores,            
            columns=['國文', '英文', '數學', '地理', '歷史'],
            index=range(1,51))

names_df:DataFrame = pd.read_csv('students.csv')
scores_df[['姓名','性別']] = names_df[['姓名','性別']].head(n=50).values
scores_df = scores_df[['姓名', '性別','國文', '英文', '數學', '地理', '歷史']]
#選取欄
scores_df[['姓名','國文']]
#選取列
scores_df.iloc[5]
scores_df.iloc[5:10]

     姓名 性別  國文  英文  數學  地理  歷史
6   朱冠霖  男  68  90  71  67  55
7   謝欣蓉  女  55  76  86  99  59
8   羅淑芬  女  52  71  79  73  68
9   許美慧  女  70  64  88  84  77
10  廖志豪  男  96  79  64  99  76

In [13]:
def get_failing_subjects(row):
    subjects = ['國文', '英文', '數學', '地理', '歷史']
    failing = [subj for subj in subjects if row[subj] < 60]    
    return ','.join(failing) if failing else "無"
    
    
scores_df["不及格的科目名稱"] = scores_df[['國文', '英文', '數學', '地理', '歷史']].apply(get_failing_subjects,axis=1)
scores_df

     姓名 性別   國文   英文  數學   地理   歷史   總分    平均    排名  及格的科目數        不及格的科目名稱
1   劉彥宏  男   99   72  86   55   84  396  79.2   5.0       1              地理
2   曾彥廷  男   67   63  63   67   57  317  63.4  39.0       1              歷史
3   吳子睿  男   86   74  73   56   54  343  68.6  28.0       2           地理,歷史
4   蕭志明  男   60   49  89  100   42  340  68.0  30.0       2           英文,歷史
5   王文傑  男   41   55  89   92   78  355  71.0  22.0       2           國文,英文
6   朱冠霖  男   48   96  43   42   93  322  64.4  36.0       3        國文,數學,地理
7   謝欣蓉  女   90  100  47   41   68  346  69.2  27.0       2           數學,地理
8   羅淑芬  女   85   97  82   98   82  444  88.8   1.0       0               無
9   許美慧  女   88   62  91   85   61  387  77.4   7.0       0               無
10  廖志豪  男   98   96  71   48   59  372  74.4  12.0       2           地理,歷史
11  葉柏翰  男   83   98  83   53   52  369  73.8  14.0       2           地理,歷史
12  呂承恩  男   88   52  54   65   94  353  70.6  23.0       2           英文,數學
13  蘇雅婷  女   92   47  45   93   49  326  65.2  34.0       3        英文,數學,歷史
14  高浩宇  男   61   99  54   50   58  322  64.4  36.0       3        數學,地理,歷史
15  王婉茹  女   83   87  46   69   67  352  70.4  24.0       1              數學
16  莊承翰  男   54   61  72   92   79  358  71.6  19.0       1              國文
17  黃裕傑  男   59   63  68   42  100  332  66.4  33.0       2           國文,地理
18  王冠廷  男   96   88  53   58   93  388  77.6   6.0       2           數學,地理
19  呂婉慧  女   59   75  75   73   86  368  73.6  15.0       1              國文
20  莊子謙  男   48   82  97   59   98  384  76.8   9.0       2           國文,地理
21  蘇彥宏  男   42   95  49   45   76  307  61.4  43.0       3        國文,數學,地理
22  李柏融  男   43   40  55   48   51  237  47.4  50.0       5  國文,英文,數學,地理,歷史
23  曾明軒  男  100   83  70   81   66  400  80.0   4.0       0               無
24  呂佳瑩  女   50   65  98   94   80  387  77.4   7.0       1              國文
25  洪怡君  女   43   44  82   91   91  351  70.2  25.0       2           國文,英文
26  洪柏宏  男   71   87  86   63   67  374  74.8  11.0       0               無
27  江雅琪  女   48   95  95   68   55  361  72.2  18.0       2           國文,歷史
28  郭怡萱  女   57   53  79   47   86  322  64.4  36.0       3        國文,英文,地理
29  簡婉慧  女   60   77  50   65   60  312  62.4  41.0       1              數學
30  楊靜宜  女   61   99  55   62   87  364  72.8  16.0       1              數學
31  曾靜儀  女   44   55  73   84   85  341  68.2  29.0       2           國文,英文
32  蕭怡伶  女   62   52  84   42   86  326  65.2  34.0       2           英文,地理
33  洪裕豪  男   46   50  98   52   62  308  61.6  42.0       3        國文,英文,地理
34  簡建宏  男   76   63  79   90  100  408  81.6   3.0       0               無
35  劉浩然  男   48   48  40   59   51  246  49.2  49.0       5  國文,英文,數學,地理,歷史
36  蕭浩宇  男   58   55  73   63   54  303  60.6  44.0       3        國文,英文,歷史
37  呂怡靜  女   82   72  97   56   70  377  75.4  10.0       1              地理
38  邱宗翰  男   80   59  92   66   61  358  71.6  19.0       1              英文
39  彭美慧  女   56   60  48   72   98  334  66.8  32.0       2           國文,數學
40  劉靜芬  女   46   46  49   55   96  292  58.4  47.0       4     國文,英文,數學,地理
41  許淑芬  女   79   64  97   55   56  351  70.2  25.0       2           地理,歷史
42  邱裕豪  男   54   81  67   62   94  358  71.6  19.0       1              國文
43  吳雅萍  女   42   62  55   95   44  298  59.6  45.0       3        國文,數學,歷史
44  施子軒  男   75   79  90   92   83  419  83.8   2.0       0               無
45  莊柏融  男   47   41  80   49   81  298  59.6  45.0       3        國文,英文,地理
46  鍾浩銘  男   64   65  50   99   85  363  72.6  17.0       1              數學
47  周美玲  女   52   45  44   98   96  335  67.0  31.0       3        國文,英文,數學
48  劉婉婷  女   75   41  94   99   61  370  74.0  13.0       1              英文
49  曾明哲  男   50   47  70   73   76  316  63.2  40.0       2           國文,英文
50  詹柏翰  男   45   49  93   47   47  281  56.2  48.0       4     國文,英文,地理,歷史

In [14]:
[subj for subj in [30, 40, 50] if subj <= 40] #list綜合表達式
fallings = []
','.join(fallings) if fallings else "無"

'無'

In [4]:
import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

#scores:ndarray | None = None # 學生的分數
#scores_df:DataFrame | None = None # 學生分數的DataFrame

scores:ndarray = np.random.randint(40, 101, size=(50, 5))
scores_df:DataFrame = pd.DataFrame(scores,            
            columns=['國文', '英文', '數學', '地理', '歷史'],
            index=range(1,51))

names_df:DataFrame = pd.read_csv('students.csv')
scores_df[['姓名','性別']] = names_df[['姓名','性別']].head(n=50).values
scores_df = scores_df[['姓名', '性別','國文', '英文', '數學', '地理', '歷史']]
#選取欄
scores_df[['姓名','國文']]
#選取列
scores_df.iloc[5]
scores_df.iloc[5:10]

     姓名 性別  國文  英文  數學  地理  歷史
6   朱冠霖  男  96  58  75  74  73
7   謝欣蓉  女  94  82  64  95  96
8   羅淑芬  女  83  46  48  44  70
9   許美慧  女  60  75  65  79  83
10  廖志豪  男  90  47  80  74  88

In [5]:
scores_df[scores_df['姓名'] == '許美慧']
scores_df[scores_df['國文'] < 60]

     姓名 性別  國文  英文  數學  地理   歷史
1   劉彥宏  男  45  50  49  41   84
3   吳子睿  男  52  58  40  41   82
4   蕭志明  男  57  84  53  98   61
13  蘇雅婷  女  42  69  72  65   43
14  高浩宇  男  54  52  97  87   97
16  莊承翰  男  47  56  94  77   87
20  莊子謙  男  57  50  63  52   78
22  李柏融  男  42  89  43  78   74
23  曾明軒  男  53  61  59  78   69
28  郭怡萱  女  44  64  96  95   83
29  簡婉慧  女  49  98  63  81   92
33  洪裕豪  男  53  90  74  65   86
36  蕭浩宇  男  45  70  41  85  100
39  彭美慧  女  58  58  54  83   97
40  劉靜芬  女  58  74  93  41   45
41  許淑芬  女  51  51  70  79   92
47  周美玲  女  41  84  71  89   95
50  詹柏翰  男  49  62  48  92   97

In [7]:
scores_df.query('國文 < 60 and 性別 == "女"')

     姓名 性別  國文  英文  數學  地理  歷史
13  蘇雅婷  女  42  69  72  65  43
28  郭怡萱  女  44  64  96  95  83
29  簡婉慧  女  49  98  63  81  92
39  彭美慧  女  58  58  54  83  97
40  劉靜芬  女  58  74  93  41  45
41  許淑芬  女  51  51  70  79  92
47  周美玲  女  41  84  71  89  95

In [8]:
scores_df[scores_df['姓名'] == '許美慧']
scores_df[scores_df['國文'] < 60]
scores_df.query("性別 == '女' and 國文 < 60 ")

     姓名 性別  國文  英文  數學  地理  歷史
13  蘇雅婷  女  42  69  72  65  43
28  郭怡萱  女  44  64  96  95  83
29  簡婉慧  女  49  98  63  81  92
39  彭美慧  女  58  58  54  83  97
40  劉靜芬  女  58  74  93  41  45
41  許淑芬  女  51  51  70  79  92
47  周美玲  女  41  84  71  89  95

In [5]:
scores_df["總分"] = scores_df[['國文', '英文', '數學', '地理', '歷史']].sum(axis=1)
scores_df["平均"] = scores_df[['國文', '英文', '數學', '地理', '歷史']].mean(axis=1)
scores_df["排名"] = scores_df["總分"].rank(ascending=False,method='min')
scores_df.sort_values(by='排名')

NameError: name 'scores_df' is not defined